# **Clase 1:** Introducción a Pandas

### value.counts() y .describe()

### Cargar las librerías

Importar la librería Pandas y definimos los datos

In [6]:
import pandas as pd 

datos = {
    'Producto': ['Laptop', 'Teclado', 'Laptop', 'Monitor', 'Teclado', 'Mouse', 'Monitor', 'Laptop'],
    'Categoria': ['Electrónica', 'Accesorios', 'Electrónica', 'Electrónica', 'Accesorios', 'Accesorios', 'Electrónica', 'Electrónica'],
    'Region': ['Norte', 'Sur', 'Norte', 'Este', 'Sur', 'Norte', 'Este', 'Sur'],
    'Precio_Unitario': [1200, 45, 1100, 300, 50, 25, 320, 1250],
    'Cantidad': [2, 10, 1, 4, 12, 60, 2, 9],
    'Sueldo': [4500, 3200, 6000, 2800, 5200, 1900, 4100, 7500]
}

#### Creamos el data frame con los datos propuestos

In [7]:
df = pd.DataFrame(datos)

#### Visualizamos las primeras 5 filas

In [4]:
df.head()

  Producto    Categoria Region  Precio_Unitario  Cantidad  Sueldo
0   Laptop  Electrónica  Norte             1200         2    4500
1  Teclado   Accesorios    Sur               45        10    3200
2   Laptop  Electrónica  Norte             1100         1    6000
3  Monitor  Electrónica   Este              300         4    2800
4  Teclado   Accesorios    Sur               50        12    5200

#### Funcion .describe()
hace operaciones con cada conjunto de elementos que tiene solo números (int/float) como max, min, mean, etc.

In [ ]:


df.describe()

       Precio_Unitario  Cantidad       Sueldo
count         8.000000   8.00000     8.000000
mean        536.250000  12.50000  4400.000000
std         548.964935  19.63961  1818.947891
min          25.000000   1.00000  1900.000000
25%          48.750000   2.00000  3100.000000
50%         310.000000   6.50000  4300.000000
75%        1125.000000  10.50000  5400.000000
max        1250.000000  60.00000  7500.000000

In [8]:
df['Sueldo'].describe() #--> SOLO PARA UNA COLUMNA, en este caso la columna 'sueldo'

count       8.000000
mean     4400.000000
std      1818.947891
min      1900.000000
25%      3100.000000
50%      4300.000000
75%      5400.000000
max      7500.000000
Name: Sueldo, dtype: float64

#### Funcion _value.counts()
número de coincidencias que hay en una columna de cada elemento

In [11]:
df['Producto'].value_counts()

Producto
Laptop     3
Teclado    2
Monitor    2
Mouse      1
Name: count, dtype: int64

## EJERCICIOS

1. Promedio de Sueldos: Utiliza la función correspondiente para obtener únicamente la media (promedio) de la columna Sueldo. (Pista: puedes usar df['Sueldo'].mean()).

In [15]:
df['Sueldo'].mean()

np.float64(4400.0)

2. Conteo por Región: Usa .value_counts() para descubrir cuál es la región que tiene más registros en la tabla.

In [ ]:
df['Region'].value_counts()
'las regiones que tienen más coincidencias es norte y sur'

Region
Norte    3
Sur      3
Este     2
Name: count, dtype: int64

3. Resumen de Cantidad: Aplica .describe() solo sobre la columna Cantidad y responde: ¿cuál es el valor máximo vendido?

In [ ]:
df['Cantidad'].describe()
'el valor máximo es 60'

count     8.00000
mean     12.50000
std      19.63961
min       1.00000
25%       2.00000
50%       6.50000
75%      10.50000
max      60.00000
Name: Cantidad, dtype: float64

4. Frecuencias Relativas (Porcentajes): Investiga qué sucede si ejecutas df['Categoria'].value_counts(normalize=True). ¿Qué representan los números resultantes y cómo los interpretarías en un informe?

In [23]:
df['Categoria'].value_counts(normalize=True)

Categoria
Electrónica    0.625
Accesorios     0.375
Name: proportion, dtype: float64